# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="awesomepanda"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=15

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  git-flow
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

# Preferred terminal for local and remote sessions
if [ "$TMUX" = "" ]; then tmux; fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# SSH - Servers
alias siv-test="ssh -i '$HOME/Projects/Aws/siv/siv-test.pem' ubuntu@ec2-34-199-133-8.compute-1.amazonaws.com"
alias siv-web-production="ssh -i '$HOME/Projects/Aws/siv/siv-production.pem' ubuntu@ec2-34-192-9-97.compute-1.amazonaws.com"
alias siv-api-gateway="ssh -i '$HOME/Projects/AWS/siv/siv-production.pem' ubuntu@ec2-18-206-88-104.compute-1.amazonaws.com"
alias siv-api-production="ssh -i '$HOME/Projects/Aws/siv/siv-production.pem' ubuntu@ec2-18-205-35-42.compute-1.amazonaws.com"
alias siv-sentry-production="ssh -i '$HOME/Projects/Aws/siv/siv-production.pem' ubuntu@ec2-54-165-59-81.compute-1.amazonaws.com"
alias siv-elasticsearch-production="ssh -i '$HOME/Projects/Aws/siv/siv-elk-production.pem' ubuntu@ec2-35-170-169-210.compute-1.amazonaws.com"

alias tim-api-production="ssh -i '$HOME/Projects/Aws/tim/tim-apps-production.pem' ubuntu@ec2-52-90-234-235.compute-1.amazonaws.com"
alias tim-smart-test="ssh -i '$HOME/Projects/Aws/tim-smart/tim-test-environment.pem' ubuntu@ec2-35-171-58-199.compute-1.amazonaws.com"

alias scs-test="ssh -i '$HOME/Projects/Aws/scs/scs-test.pem' ubuntu@ec2-18-214-27-219.compute-1.amazonaws.com"
alias scs-web-production="ssh -i '$HOME/Projects/Aws/scs/scs-web-production.pem' ubuntu@ec2-18-232-194-35.compute-1.amazonaws.com"

# PHP aliases
alias phpunit-watcher="ag -l | entr -rc vendor/bin/phpunit --printer='Codedungeon\\PHPUnitPrettyResultPrinter\\Printer'"
alias artisan="php artisan"

# General aliases
alias watcher="ag -l | entr -rc"
alias cat=ccat

# Exporting Composer path.
export PATH="$PATH:$HOME/.config/composer/vendor/bin"

# Exporting Laravel path.
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Exporting NVM path.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Exporting sbin path.
export PATH="/usr/local/sbin:$PATH"

export PATH="~/.local/bin:$PATH"

# Exporting bin path.
export PATH="/usr/local/bin:$PATH"

# Export Android HOME.
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/jacksonflorentino/.sdkman"
[[ -s "/Users/jacksonflorentino/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jacksonflorentino/.sdkman/bin/sdkman-init.sh"

# if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
